{
 "title": "Boleto API PROD",
 "tags": [
  "external",
  "boleto"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Threads",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"num-goroutines\")) AS \"last_num-goroutines\" FROM \"boleto-api\".\"runtime\".\"metrics\" WHERE time > now() - 5s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "deckbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"memory-alloc\") AS \"last_memory-alloc\" FROM \"boleto-api\".\"runtime\".\"metrics\" WHERE time > now() - 5m",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"request-time\") AS \"mean_request-time\" FROM \"boleto-api\".\"runtime\".\"timing\" WHERE time > now() - 30m GROUP BY time(20s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Boletos Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"BancoDoBrasil-status\") + count(\"BradescoNetEmpresa-status\") + count(\"Caixa-status\") + count(\"Citibank-status\") + count(\"Itau-status\") + count(\"Santander-status\") FROM \"boleto-api\".\"business\".\"boletos\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bradesco NetEmpresa Reg Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"bradesco-netempresa-register-boleto-online\") AS \"mean_bradesco-netempresa-register-boleto-online\" FROM \"boleto-api\".\"runtime\".\"timing\" WHERE time > now() - 30m GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Itaú Ticket Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"itau-get-ticket-boleto-time\") AS \"mean_itau-get-ticket-boleto-time\" FROM \"boleto-api\".\"runtime\".\"timing\" WHERE time > now() - 30m GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Itaú Reg Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"itau-register-boleto-time\") AS \"mean_itau-register-boleto-time\" FROM \"boleto-api\".\"runtime\".\"timing\" WHERE time > now() - 30m GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BB Login Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"bb-login-time\") AS \"mean_bb-login-time\" FROM \"boleto-api\".\"runtime\".\"timing\" WHERE time > now() - 30m GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BB Reg Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"bb-register-boleto-time\") AS \"mean_bb-register-boleto-time\" FROM \"boleto-api\".\"runtime\".\"timing\" WHERE time > now() - 30m GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Santander Ticket Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"santander-get-ticket-boleto-time\") AS \"mean_bb-register-boleto-time\" FROM \"boleto-api\".\"runtime\".\"timing\" WHERE time > now() - 30m GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Santander Reg Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"santander-register-boleto-time\") AS \"mean_bb-register-boleto-time\" FROM \"boleto-api\".\"runtime\".\"timing\" WHERE time > now() - 30m GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Citibank Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"citibank-register-boleto-online\") AS \"mean_citibank-register-boleto-online\" FROM \"boleto-api\".\"runtime\".\"timing\" WHERE time > now() - 30m GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Caixa Reg Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"caixa-register-time\") AS \"mean_caixa-register-time\" FROM \"boleto-api\".\"runtime\".\"timing\" WHERE time > now() - 30m GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BradescoShopFacil Reg Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"bradesco-shopfacil-register-boleto-online\") AS \"mean_citibank-register-boleto-online\" FROM \"boleto-api\".\"runtime\".\"timing\" WHERE time > now() - 30m GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bradesco NetEmpresa OK >2h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"BradescoNetEmpresa-status\") AS \"registred Itau\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 2h AND \"BradescoNetEmpresa-status\"=200",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Itaú OK >2h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Itau-status\") AS \"registred Itau\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 2h AND \"Itau-status\"=200",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BB OK >2h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"BancoDoBrasil-status\") AS \"registred Banco do Brasil \" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 2h AND \"BancoDoBrasil-status\"=200",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Santander OK >2h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Santander-status\") AS \"registred Santader\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 2h AND \"Santander-status\"=200",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Citibank OK >2h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Citibank-status\") AS \"registred Citibank\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 2h AND \"Citibank-status\"=200",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Caixa OK >2h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Caixa-status\") AS \"registred Caixa\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 1h AND \"Caixa-status\"=200",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BradescoShopFacil OK >2h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"BradescoShopFacil-status\") AS \"registred ShopFacil\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 2h AND \"BradescoShopFacil-status\"=200",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bradesco NetEmpresa NOK >2h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"BradescoNetEmpresa-status\") AS \"registred BradescoNetEmpresa\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 2h AND \"BradescoNetEmpresa-status\"<>200",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Itaú NOK >2h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Itau-status\") AS \"registred Santander\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 2h AND \"Itau-status\"<>200",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BB NOK >2h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"BancoDoBrasil-status\") AS \"bad-request Banco do Brasil \" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 2h AND \"BancoDoBrasil-status\"<>200",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Santander NOK >2h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Santander-status\") AS \"registred Santander\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 2h AND \"Santander-status\"<>200",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Citibank NOK>2h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Citibank-status\") AS \"registred Citibank\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 2h AND \"Citibank-status\"<>200",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Caixa NOK >2h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Caixa-status\") AS \"registred Caixa\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 2h AND \"Caixa-status\"=400",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BradescoShopFacil NOK >2h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"BradescoShopFacil-status\") AS \"registred Bradesco\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 2h AND \"BradescoShopFacil-status\"<>200",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bradesco NetEmpresa Errors x Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"BradescoNetEmpresa-status\") AS \"errors\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 24h AND \"BradescoNetEmpresa-status\"<>200 Group by time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"BradescoNetEmpresa-status\") AS \"success\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 24h AND \"BradescoNetEmpresa-status\"=200 Group by time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BradescoShopFacil Errors x Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"BradescoShopFacil-status\") AS \"errors\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 24h AND \"BradescoShopFacil-status\"<>200 Group by time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"BradescoShopFacil-status\") AS \"success\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 24h AND \"BradescoShopFacil-status\"=200 Group by time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Citibank Errors x Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Citibank-status\") AS \"errors\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 24h AND \"Citibank-status\"<>200 Group by time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Citibank-status\") AS \"success\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 24h AND \"Citibank-status\"=200 Group by time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Santander Errors x Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Santander-status\") AS \"errors\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 24h AND \"Santander-status\"<>200 Group by time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Santander-status\") AS \"success\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 24h AND \"Santander-status\"=200 Group by time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Itaú Errors x Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Itau-status\") AS \"errors\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 24h AND \"Itau-status\"<>200 Group by time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Itau-status\") AS \"success\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 24h AND \"Itau-status\"=200 Group by time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Banco do Brasil Errors x Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"BancoDoBrasil-status\") AS \"errors\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 24h AND \"BancoDoBrasil-status\"<>200 Group by time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"BancoDoBrasil-status\") AS \"success\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 24h AND \"BancoDoBrasil-status\"=200 Group by time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Caixa Errors x Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Caixa-status\") AS \"errors\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 24h AND \"Caixa-status\"<>200 Group by time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Caixa-status\") AS \"success\" FROM \"boleto-api\".\"business\".\"boletos\" WHERE time > now() - 24h AND \"Caixa-status\"=200 Group by time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API Time Series",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"request-time\") AS \"mean_request-time\" FROM \"boleto-api\".\"runtime\".\"timing\" GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Allocated Series",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory-alloc\") AS \"mean_memory-alloc\" FROM \"boleto-api\".\"runtime\".\"metrics\" GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}